package de.unistuttgart.hamster.vimotest;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import java.io.IOException;
import org.junit.jupiter.api.Assertions;

public class HamsterViewTests extends HamsterViewTestBase {

  @Test
  public void GIVENExample013X3GridWHENLoadTerritoryTHENTerritoryShows3X3GridANDOnlyPauseButtonIsSensitive() throws IOException {
    loadTerritory("example.ter");
    assert_territory_TableCheck_a0();
    assert_buttons_TableCheck_b0();
    assert_mouthEmpty_c0();
    assert_grainAvailable_d0();
  }

  public void move() {
  }
  private void movePaule() {
    // call movePaule
  }
  public void assert_territory_TableCheck_a0() {
    {
      var cell0_0 = viewModel.getRows().get(0).getCells().get(0);
      var cell0_0_0 = cell0_0.getLayers().get(0).getImageName();
      Assertions.assertEquals("Wall", cell0_0_0);
      // assert cell 0,0
      // assert cell 1,0
      // assert cell 2,0
      // assert cell 0,1
      // assert cell 1,1
      // assert cell 2,1
      // assert cell 0,2
      // assert cell 1,2
      // assert cell 2,2
    }
  }
  public void assert_buttons_TableCheck_b0() {
    {
      int a = 0;
      Object viewModel = null;

      // assert cell 0,0
      // assert cell 1,0
      // assert cell 2,0
      // assert cell 3,0
    }
  }
  public void assert_mouthEmpty_c0() {
    Assertions.assertEquals(true, paule.mouthEmpty());
  }
  public void assert_grainAvailable_d0() {
    Assertions.assertEquals(false, paule.grainAvailable());
  }

  /*package*/ int myVar;
}
